# Generated by Django 3.2.6 on 2021-08-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
