# Generated by Django 3.2.6 on 2021-09-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0009_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='cake_image',
            new_name='seller_image',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cake_name',
            new_name='seller_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cake_price',
            new_name='seller_price',
        ),
    ]
