# Generated by Django 3.2.6 on 2021-09-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0012_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
