# Generated by Django 3.2.6 on 2021-09-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0016_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.cake'),
        ),
    ]
