# Generated by Django 3.2.6 on 2021-09-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0017_alter_cart_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='seller',
        ),
    ]
