# Generated by Django 3.2.6 on 2021-09-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_forget_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forget_password_token',
        ),
    ]
